### ISSUE TITLE
Where is 1.0.0-beta-1 built from?  

### ISSUE THREAD

**Issue by gouldner** [kakawait/cas-security-spring-boot-starter#115]
I want to view with the code that was used to build the 1.0.0-beta-1 release.

There is no branch or tag that I can find which was used to build this version.

How can I see the commit used to build this version?

**Comment by kakawait** [comment]
Is develop. The only diff is version on pom.xml but code is same

**Comment by gouldner** [comment]
But you added code to develop for the change I requested.  That isn't in 1.0.0-beta-1  correct.

You told me to build develop to test the new features and you would add them to 1.0.0-beta-2 if they worked.  

I am finding my code works with 1.0.0-beta-1 (pulled from maven) which should NOT include the change for issue 108 as well as building 1.0.0-SNAPSHOT which does include the changes.

So I am trying to compare the code between 1.0.0-beta-1 which was released to maven and 1.0.0-SNAPSHOT built from develop branch which I believe should not be the same.

So which commit on develop was actually used to release to maven?

**Comment by kakawait** [comment]
Yeap sorry i forget. I push manually beta 1 from that last commit fe6f78c7039ed145d62bcd8ea0cdf7035b3b5dfe

**Comment by kakawait** [comment]
Between beta 1 and Snapshot the only thing i did is fixing NPE and exposing AuthenticationManagerBuilder

**Comment by kakawait** [comment]
I'll add tag tomorrow because i dont have computer atm

**Comment by kakawait** [comment]
https://github.com/kakawait/cas-security-spring-boot-starter/releases/tag/1.0.0-beta-1
