### ISSUE TITLE
Does it support set `ignorePattern`

### ISSUE THREAD

**Issue by xuande** [kakawait/cas-security-spring-boot-starter#118]

**Comment by kakawait** [comment]
@xuande could you please add more details? I'm not sure to understand your request

**Comment by xuande** [comment]
The URI in `ignorePattern` does not require authentication

**Comment by kakawait** [comment]
@xuande there is no built-in property for ignoring (but there is one for selecting path to secure `security.cas.paths` which is default to `/**` aka _everything_).

After it depends what do you mean by ignoring?

1. You don't want CAS authentication
2. You don't want any security filters

Both could be done programmatically

**Comment by xuande** [comment]
@kakawait Got it. Thanks for your reply.
