### ISSUE TITLE
Problem with Logout

### ISSUE THREAD

**Issue by zematrix** [kakawait/cas-security-spring-boot-starter#158]
Hi,

I'm using 1.0.6 version.

I configured my application with these three entries

```
security.cas.server.base-url=my-cas-server-url
security.cas.server.protocol-version=2
security.cas.service.resolution-mode=dynamic
```

The only other config i have is related to CORS.

```
@Configuration
public class MvcConfig implements WebMvcConfigurer {

    @Value("${static.resources.location}")
    private String staticResourcesLocation;

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/static/**").addResourceLocations(staticResourcesLocation);
    }

    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*.mycompany.com");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        return new CorsFilter(source);
    }

}
```
Everything works perfectly, except when i want to trigger logout. Calling my application's url with the `/logout` path returns me a 404.

Trying to explicitly set the logout url as `security.cas.service.paths.logout=/logout' still doesn't work. 

What can i do to make my Spring Boot application detect `/logout` as a logout instruction to CAS?

**Comment by kakawait** [comment]
By default spring logout is on `POST` and not `GET`

Can you please test with such configuration https://github.com/kakawait/cas-security-spring-boot-starter/blob/master/cas-security-spring-boot-sample/src/main/java/com/kakawait/sample/CasSecuritySpringBootSampleApplication.java#L127 ?

**Comment by zematrix** [comment]
Solid!! That solved my problem.

Thank you.

**Comment by kakawait** [comment]
Great
