### ISSUE TITLE
Support Spring boot 2.0

### ISSUE THREAD

**Issue by kakawait** [kakawait/cas-security-spring-boot-starter#32]
Need to tests (help wanted) I even didn't try, it may already work (but I got some doubt)

**Comment by igorhara** [comment]
I tried to use your client in a 2.0.1 spring boot project and it would not compile. IT seems that the package uses some classes that does not exist anymore in version 2 of spring boot.

**Comment by kakawait** [comment]
@igorhara Thank you for your feedback. Yeah because I was using class that does not exist anymore on SB2.

Roadmap is `RestTemplate` support then I will work on Spring Boot 2 support

**Comment by Holm78** [comment]
I meet with the same problem using spring boot 2.0.1 - incompatible constructor is used for  instantiation of InMemoryUserDetailsManager.

**Comment by kakawait** [comment]
@Holm78 Thank you for feedback. I'm currently working on coverage (see `develop` I finished near 100% for `spring-security-cas-extension`, now missing `cas-security-spring-boot-autoconfigure` module) then I will start working on _Spring boot 2_ support.

Because I think I also will have issue with `SecurityProperties` that has changed from `1` to `2`.

To be honest I hope 1 month to get Spring boot 2 support (only working on spare time)

**Comment by kakawait** [comment]
@igorhara @Holm78 I start working on Spring boot 2 support on #94 

Not completely finished but I think you could start trying if you want.

For instance nothing on _maven central_ you have to install with `mvn clean install`

**Comment by kakawait** [comment]
@igorhara @Holm78 @liyiorg @ankitwashere I just upload 

```
<dependency>
  <groupId>com.kakawait</groupId>
  <artifactId>cas-security-spring-boot-starter</artifactId>
  <version>1.0.0-beta-1</version>
</dependency>
```

for Spring boot 2 support.

Please checkout https://github.com/kakawait/cas-security-spring-boot-starter/blob/master/CHANGELOG.md for **breaking changes**

(please wait few minutes to be spread over spring central)
