### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by javasenior** [kakawait/cas-security-spring-boot-starter#51]
Could you dockerize project?

**Comment by kakawait** [comment]
@javasenior could you elaborate more on what do you want to dockerize since _cas security spring boot starter_ is a library not an application. Maybe the sample demo?

**Comment by javasenior** [comment]
Yes, not for the whole project but a sample demo for _cas-security-spring-boot-sample_ will be helpful.

**Comment by coskundeniz89** [comment]
I think it must be like this. https://github.com/kakawait/cas-security-spring-boot-starter/issues/52#issuecomment-321819807
