### ISSUE TITLE
Login redirect

### ISSUE THREAD

**Issue by coskundeniz89** [kakawait/cas-security-spring-boot-starter#52]
Hi @kakawait. You published new version. But there is a same bug again. When you done #14 issue it was fixed. There is also the same error in UI. Could you fix this? I think you must not to redirect login page. Maybe you can add a property to config for login page.

**Comment by kakawait** [comment]
@coskundeniz89 I'm not sure to understand because I tried both scenario using [sample project]() and I don't have any issue related to #14 scenario.

What I tried:

1. Get a `TGT` using following CAS api

```
> POST /cas/v1/tickets HTTP/1.1
> Host: CAS_SERVER
> Content-Type: application/x-www-form-urlencoded
Accept: application/json
```

2. Then ask a service ticket for my service `http://localhost:8080/api`

```
> POST /cas/v1/tickets/TGT-1-XJv0iB6SM11NRPyFnM6cjzwQHQ7YCpmR33GTdNiE2yBQYk0xsm-33188ef14bbf HTTP/1.1
> Host: CAS_SERVER
> Content-Type: application/x-www-form-urlencoded
| service=http%3A%2F%2Flocalhost%3A8080%2Fapi
```

3. Call service using the previous _service ticket_

```
# REQUEST
> GET /api?ticket=ST-2-a1iRq3gpa9dHhz6nnK7a-33188ef14bbf HTTP/1.1
> Host: localhost:8080

# RESPONSE
< HTTP/1.1 302 
< Set-Cookie: JSESSIONID=4DD9341A23F1C122F1E93A3FC56171A7; Path=/; HttpOnly
< Location: http://locahost:8080/api
```

Then after 302 to `http://locahost:8080/api` without issue! That prints

> Hello, <username>!

---

Could you please provides me a sample a more detailed scenario? And are you using latest version `0.4.4`?

**Comment by coskundeniz89** [comment]
Hi @kakawait , i think i cant understand this problem. I havent got a problem for rest login it works. But I have problem with browser login. I do this steps:

1. I enter "**https://localhost:8443/protected**" url to browser. 
2. After i redirected to "**https://localhost:10100/cas/login?service=https%3A%2F%2Flocalhost%3A8443%2Flogin**" url
3. I enter correct username and password. 
4. Cas redirect "**https://localhost:8443/login?ticket=ST-18-SeI241tPdEc63Y4kVCrL-dd32f4917ef6**" 

I havent got login page. I was expecting to go to "/protected" page. But it doesnt. 


I experienced the same thing #14 . Now rest api authentication works, but page ui authentication doesnt work

**Comment by coskundeniz89** [comment]
And you can see this project. 
https://github.com/coskundeniz89/my-cas-client

**Comment by kakawait** [comment]
I'm currently out of computer & internet. I will check it as soon I can get both. Please be patient or downgrade version

**Comment by coskundeniz89** [comment]
I think you can do your configuration like unicon. Base-url can change for environment and you should not interfere "login" and other urls. If you can do this, #51 issue will also be fixed.

security.cas.server-url-prefix=https://cashost.com/cas
security.cas.server-login-url=https://cashost.com/cas/login
security.cas.client-host-url=https://casclient.com

**Comment by coskundeniz89** [comment]
Hi @kakawait . I removed security.cas.paths from yml. It is work now. It doesnt redirect to login url (ui and rest).
