### ISSUE TITLE
CAS logout custom configuration logout success url?

### ISSUE THREAD

**Issue by liyiorg** [kakawait/cas-security-spring-boot-starter#72]
Hello  , @kakawait 
The user logout success default url is  http://cas.mydomain.com/cas/logout.

How configuration logout success ,and go to service url.

Like this:

http://cas.mydomain.com/cas/logout?service=http://www.google.com

Thanks!

**Comment by kakawait** [comment]
@liyiorg Hi

You are true I keep the default _logout success handler_ that only redirect you on `http://cas.mydomain.com/cas/logout` as describe on documentation https://docs.spring.io/spring-security/site/docs/current/reference/html/cas.html

So you must define your own `LogoutSuccessHandler` you can find sample here 

https://github.com/kakawait/cas-security-spring-boot-starter/commit/f25425c7ad8b9c8af36ded9525436f6d59a9aaef
