### ISSUE TITLE
Unresolved dependency on cas-security-spring-boot-parent 0.7.0

### ISSUE THREAD

**Issue by Holm78** [kakawait/cas-security-spring-boot-starter#86]
Latest release 0.7.0 can't be used due to unresolved dependency on cas-security-spring-boot-parent 0.7.0:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve com.kakawait:cas-security-spring-boot-starter:0.7.0.
  Required by:
      project :
   > Could not resolve com.kakawait:cas-security-spring-boot-starter:0.7.0.
      > Could not parse POM https://repo.maven.apache.org/maven2/com/kakawait/cas-security-spring-boot-starter/0.7.0/cas-security-spring-boot-starter-0.7.0.pom
         > Could not find com.kakawait:cas-security-spring-boot-parent:0.7.0.
           Searched in the following locations:
               https://repo.maven.apache.org/maven2/com/kakawait/cas-security-spring-boot-parent/0.7.0/cas-security-spring-boot-parent-0.7.0.pom
               https://repo.maven.apache.org/maven2/com/kakawait/cas-security-spring-boot-parent/0.7.0/cas-security-spring-boot-parent-0.7.0.jar
               https://jcenter.bintray.com/com/kakawait/cas-security-spring-boot-parent/0.7.0/cas-security-spring-boot-parent-0.7.0.pom
               https://jcenter.bintray.com/com/kakawait/cas-security-spring-boot-parent/0.7.0/cas-security-spring-boot-parent-0.7.0.jar
   > Could not resolve com.kakawait:cas-security-spring-boot-starter:0.7.0.
      > Could not parse POM https://jcenter.bintray.com/com/kakawait/cas-security-spring-boot-starter/0.7.0/cas-security-spring-boot-starter-0.7.0.pom
         > Could not find com.kakawait:cas-security-spring-boot-parent:0.7.0.

**Comment by kakawait** [comment]
Thank you. I may understand why, is related to recent refactoring on pom.xml. I will push 0.7.1 soon

**Comment by kakawait** [comment]
I tried to repush only missing _parent pom_ but still pending on maven central. If nothing in next your I will push new release.

Sorry for that. My local `~/.m2/repository` hide that issue

**Comment by Holm78** [comment]
Thank you

**Comment by kakawait** [comment]
@Holm78 I just repushed `0.7.1`. Please wait somes mins / hours to be sure that _central maven_ will be refreshed

**Comment by Holm78** [comment]
thank you, it works!

**Comment by kakawait** [comment]
I may create a new `0.7.2` to fix something on `pom.xml` but as end-user is not worth-it to upgrade because no real change, just cleaning thing on `pom.xml`
