### ISSUE TITLE
Spring boot 2 start-up error  

### ISSUE THREAD

**Issue by liyiorg** [kakawait/cas-security-spring-boot-starter#92]
Some class package path changed with <code>spring-boot-starter-security</code> , Can make a branch for spring boot 2 ?

**Comment by kakawait** [comment]
@liyiorg I'm currently working on SB2 support (see #32). For what I start working on prototyping locally I think I will not create two different branches to managed both versions. But keep only 1 branch that will work for both version (with some reflection tricks to avoid some missing classes or packages).

I will close it in favor of #32
