### ISSUE TITLE
Failed to collect dependencies

### ISSUE THREAD

**Issue by ankitwashere** [kakawait/cas-security-spring-boot-starter#95]
I downloaded a spring boot app from spring initializer. Added the dependency to the POM and now my builds fail. Any idea on how to resolve this ?

Failed to execute goal on project dataAccessRequest: Could not resolve dependencies for project uk.ac.stand:dataAccessRequest:war:0.0.1-SNAPSHOT:

Failed to collect dependencies at com.kakawait:cas-security-spring-boot-starter:jar:0.8.0: 

Failed to read artifact descriptor for com.kakawait:cas-security-spring-boot-starter:jar:0.8.0: Could not find artifact com.kakawait:cas-security-spring-boot-parent:pom:0.8.0

**Comment by kakawait** [comment]
@ankitwashere Thank you for report. I pushed `0.8.0` yesterday may I miss something. Could you please try with `0.7.1`?

**Comment by kakawait** [comment]
@ankitwashere Correct there is no `0.8.0` I will try to fix it or I will create `0.8.1` if I can't re-upload on same version

**Comment by ankitwashere** [comment]
Yea 0.7.1 does not have that issue. thanks 👍

**Comment by ankitwashere** [comment]
Okay so i can build with both 0.7.1 and 0.6.1 however the application would fail to start on tomcat.

And this is where it is failing. Sorry to bother again, But any help ?

`Failed to introspect annotations on class com.kakawait.spring.boot.security.cas.CasSecurityAutoConfiguration$$EnhancerBySpringCGLIB$$40d11e40: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy`

**Comment by kakawait** [comment]
@ankitwashere I never get that issue, which version of Spring Boot do you use?

 and do you have sample application that I can use to reproduce?

**Comment by kakawait** [comment]
@ankitwashere for `0.8.0` I just pushed on maven central https://oss.sonatype.org/service/local/repositories/releases/content/com/kakawait/cas-security-spring-boot-parent/ but it can make time to be replicated everywhere.

But I don't think it will fix your issue because `0.8.0` is mainly test/coverage version

**Comment by ankitwashere** [comment]
I got my spring boot set up from https://start.spring.io/
See screenshot link for settings i used. It is very basic. then i added a controller and modified the POM as you can see below. And that is it. I just wanted to use this library to work with CAS.

https://screenshots.firefox.com/HQf4gt67ILJQTweZ/start.spring.io

POM
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>uk.ac.stand</groupId>
	<artifactId>dataAccessRequest</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>dataAccessRequest</name>
	<description>Data access request application</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.2.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>

		<spring.security.version>4.2.4.RELEASE</spring.security.version>
		<hibernate.version>5.2.13.Final</hibernate.version>
		<log4j.version>2.10.0</log4j.version>
		<jackson.version>2.9.4</jackson.version>
		
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>

	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>12.1.0.1.0</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-lgpl</artifactId>
			<version>1.9.13</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>com.kakawait</groupId>
			<artifactId>cas-security-spring-boot-starter</artifactId>
			<version>0.7.1</version>
		</dependency>
		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>
`
Controller

```
package uk.ac.stand.dataAccessRequest.controllers;


import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
public class HomeController {

    @RequestMapping("/")
    public String index() {
        return "works";
    }
    @RequestMapping("/update")
    public String update() {
        String value = "updated";
        return value;
    }
}

```

This has nothing modified in terms of spring boot config

**Comment by kakawait** [comment]
@ankitwashere Ha yes sure, the Spring Boot 2 support is not totally finished (currently in progress https://github.com/kakawait/cas-security-spring-boot-starter/pull/94).

Solutions:

1. Rollback to Spring Boot 1.5.x
2. Pull branch `feature/spring-boot-2` from https://github.com/kakawait/cas-security-spring-boot-starter/pull/94 and `mvn clean install` then use local version `1.0.0-SNAPSHOT` (but be careful work in progress can be buggy)
3. Wait few days/weeks to get official `1.0.0` version out (don't be afraid no `0.9.0` is programmed I will jump from `0.8.0` to `1.0.0`)

**Comment by ankitwashere** [comment]
Ahh okay...that explains it all.

**Comment by kakawait** [comment]
@ankitwashere I will use that issue to fix `pom.xml` to do not forget the `parent` next deploy. Thank you for reporting. 

I hope I will see you back when `1.0.0` will be out and sorry for delay I didn't find to time to release the same day as Spring Boot 2 was released
